"""remove items from batches

Revision ID: 2008f14d9580
Revises: 227d3507f0df
Create Date: 2025-08-26 20:33:35.430410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2008f14d9580'
down_revision: Union[str, Sequence[str], None] = '227d3507f0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('batches_item_id_fkey'), 'batches', type_='foreignkey')
    op.drop_column('batches', 'item_id')
    op.add_column('items', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'batch_id')
    op.add_column('batches', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('batches_item_id_fkey'), 'batches', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
