"""change batches structure

Revision ID: 2a698cbe2dea
Revises: 4b2e33c1263b
Create Date: 2025-10-19 17:52:41.014484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a698cbe2dea'
down_revision: Union[str, Sequence[str], None] = '4b2e33c1263b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('batches', sa.Column('manufacture_date', sa.Date(), nullable=True))
    op.add_column('batches', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'expiry_date')
    op.drop_column('batches', 'manufacture_date')
    op.drop_column('batches', 'quantity')
    # ### end Alembic commands ###
