"""append autoincrement in supply model

Revision ID: 47f0c632b5d1
Revises: ebc5c6fd2b85
Create Date: 2025-10-20 17:09:14.698566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f0c632b5d1'
down_revision: Union[str, Sequence[str], None] = 'ebc5c6fd2b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS supplies_id_seq")
    op.execute("ALTER TABLE supplies ALTER COLUMN id SET DEFAULT nextval('supplies_id_seq')")
    op.execute("SELECT setval('supplies_id_seq', COALESCE((SELECT MAX(id)+1 FROM supplies), 1), false)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
