"""remove batch_id from api/catalogs/items.py

Revision ID: 4b2e33c1263b
Revises: 8eae3d6b1759
Create Date: 2025-10-19 16:30:55.323510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2e33c1263b'
down_revision: Union[str, Sequence[str], None] = '8eae3d6b1759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
