"""remove batch and item relation and append batch and supply relation

Revision ID: 4fe693522b39
Revises: ca02f2133299
Create Date: 2025-10-20 14:58:41.049843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe693522b39'
down_revision: Union[str, Sequence[str], None] = 'ca02f2133299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('supply_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('batches_item_id_fkey'), 'batches', type_='foreignkey')
    op.create_foreign_key(None, 'batches', 'supplies', ['supply_id'], ['id'])
    op.drop_column('batches', 'item_id')
    op.alter_column('receivings', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receivings', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('batches', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.create_foreign_key(op.f('batches_item_id_fkey'), 'batches', 'items', ['item_id'], ['id'])
    op.drop_column('batches', 'supply_id')
    # ### end Alembic commands ###
