"""Make cell_id nullable in batches

Revision ID: 572a1749568d
Revises: fd511038d453
Create Date: 2025-08-26 18:45:04.380899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572a1749568d'
down_revision: Union[str, Sequence[str], None] = 'fd511038d453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'cell_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'cell_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
