"""working on receivings

Revision ID: 72feecd6caa2
Revises: 2008f14d9580
Create Date: 2025-10-17 21:23:57.047151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72feecd6caa2'
down_revision: Union[str, Sequence[str], None] = '2008f14d9580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivings', sa.Column('cell_id', sa.Integer(), nullable=True))
    op.add_column('receivings', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('receivings_order_id_fkey'), 'receivings', type_='foreignkey')
    op.create_foreign_key(None, 'receivings', 'manufacturers', ['manufacturer_id'], ['id'])
    op.create_foreign_key(None, 'receivings', 'cells', ['cell_id'], ['id'])
    op.drop_column('receivings', 'type')
    op.drop_column('receivings', 'quantity')
    op.drop_column('receivings', 'unit_of_measure')
    op.drop_column('receivings', 'order_id')
    op.drop_column('receivings', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivings', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('receivings', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('receivings', sa.Column('unit_of_measure', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('receivings', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('receivings', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'receivings', type_='foreignkey')
    op.drop_constraint(None, 'receivings', type_='foreignkey')
    op.create_foreign_key(op.f('receivings_order_id_fkey'), 'receivings', 'orders', ['order_id'], ['id'])
    op.drop_column('receivings', 'manufacturer_id')
    op.drop_column('receivings', 'cell_id')
    # ### end Alembic commands ###
