"""delete barcode from receivings

Revision ID: 9eb9ca3b5ee0
Revises: 8f044e6c3ab2
Create Date: 2025-08-24 11:53:33.489763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb9ca3b5ee0'
down_revision: Union[str, Sequence[str], None] = '8f044e6c3ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivings_barcode'), table_name='receivings')
    op.drop_column('receivings', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivings', sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_receivings_barcode'), 'receivings', ['barcode'], unique=True)
    # ### end Alembic commands ###
