# backend/app/core/permissions.py

# Группы и коды всех прав в системе
PERMISSIONS = {
    "warehouses": [
        ("view_warehouses", "Просмотр складов"),
        ("create_warehouse", "Создание складов"),
        ("update_warehouse", "Редактирование складов"),
        ("delete_warehouse", "Удаление складов"),
    ],
    "items": [
        ("view_items", "Просмотр номенклатуры"),
        ("create_item", "Создание товаров"),
        ("update_item", "Редактирование товаров"),
        ("delete_item", "Удаление товаров"),
    ],
    "cells": [
        ("create_cell", "Создание ячеек"),
        ("update_cell", "Редактирование ячеек"),
        ("delete_cell", "Удаление ячеек"),
    ],
    "stocks": [
        ("view_stocks", "Просмотр остатков"),
        ("view_moves", "Просмотр перемещений"),
        ("create_stock", "Пополнение остатков"),
        ("update_stock", "Редактирование остатков"),
        ("withdraw_stock", "Списание товара"),
        ("move_stock", "Перемещение товара"),
        ("delete_stock", "Удаление остатков"),
    ],
    "orders": [
        ("view_orders", "Просмотр заказов"),
        ("create_order", "Создание заказов"),
        ("update_order", "Редактирование заказов"),
        ("delete_order", "Удаление заказов"),
    ],
    "picking": [
        ("pick_item", "Отбор товаров"),
        ("update_pick", "Изменение операций отбора"),
        ("delete_pick", "Удаление операций отбора"),
        ("complete_picking", "Завершение сборки заказа"),
    ],
    "production": [
        ("view_production", "Просмотр раздела Производство"),
        ("create_production_order", "Создание заданий на производство"),
        ("update_production_order", "Редактирование заданий на производство"),
        ("delete_production_order", "Удаление заданий на производство"),
        ("request_production_supplies", "Запрос сырья и расходников для производства"),
        ("fulfill_production_supplies", "Выполнение заявок производства"),
        ("start_production", "Запуск заданий на производство"),
        ("complete_production", "Завершение заданий на производство"),
        ("transfer_production_to_stock", "Передача готовой продукции на склад"),
        ("request_production_chz", "Заказ ЧЗ для производства"),
        ("view_production_order", "Просмотр заданий на производство"),
    ],
    "marking": [
        ("view_marking", "Доступ к разделу Маркировка"),
        ("view_marking_turnover", "Просмотр раздела Оборот кодов"),
        ("view_marking_orders", "Просмотр раздела Заказ и получение"),
        ("view_marking_intro", "Просмотр раздела Ввод в оборот"),
        ("view_marking_withdrawal", "Просмотр раздела Вывод из оборота"),
        ("view_marking_chz", "Просмотр раздела Запросы ЧЗ в маркировке"),
        ("create_manual_chz_request", "Создание ручных запросов ЧЗ"),
        ("view_marking_aggregation", "Просмотр раздела Агрегация"),
        ("view_marking_shipping", "Просмотр раздела Отгрузка"),
        ("view_marking_tsd", "Просмотр раздела Задание на ТСД"),
        ("view_marking_labels", "Просмотр раздела Печать этикеток"),
        ("view_chz_registry", "Просмотр раздела ЧЗ"),
        ("delete_chz_request", "Перенос запросов ЧЗ в архив"),
    ],
    "admin": [
        ("manage_users", "Управление пользователями"),
        ("manage_roles", "Управление ролями и правами"),
        ("view_history", "Просмотр истории операций"),
        ("rollback_history", "Откат операций в истории"),
        ("view_admin_stats", "Просмотр статистики"),
    ],
}

# Маппинг системных ролей на коды прав
PERMISSIONS["production"].append(("manage_production_labor", "Учет времени в производстве"))
PERMISSIONS["employees"] = [
    ("view_employees", "Просмотр сотрудников"),
    ("manage_employees", "Управление сотрудниками"),
    ("manage_employee_shifts", "Ручная регистрация смен"),
]
PERMISSIONS["reports"] = [
    ("view_reports", "Просмотр отчетов"),
]

DEFAULT_ROLE_PERMISSIONS = {
    "admin": [code for group in PERMISSIONS.values() for code, _ in group],
    "manager": [
        code
        for group_name, perms in PERMISSIONS.items()
        for code, _ in perms
        if code not in ("manage_users", "manage_roles")
    ],
    "storekeeper": [
        "view_warehouses",
        "view_items",
        "view_stocks",
        "view_moves",
        "view_orders",
        "view_chz_registry",
        "create_manual_chz_request",
        "delete_chz_request",
        "view_production",
        "create_warehouse",
        "update_warehouse",
        "create_item",
        "update_item",
        "create_cell",
        "update_cell",
        "create_stock",
        "update_stock",
        "withdraw_stock",
        "move_stock",
        "create_order",
        "update_order",
        "pick_item",
        "update_pick",
        "delete_pick",
        "complete_picking",
        "fulfill_production_supplies",
        "transfer_production_to_stock",
        "view_production_order",
        "view_employees",
        "manage_employee_shifts",
    ],
    "operator": [
        "view_warehouses",
        "view_stocks",
        "view_orders",
        "view_history",
        "view_production",
        "view_production_order",
        "create_order",
        "update_order",
        "pick_item",
        "update_pick",
        "delete_pick",
        "complete_picking",
        "view_marking",
        "view_marking_turnover",
        "view_marking_orders",
        "view_marking_intro",
        "view_marking_withdrawal",
        "view_marking_chz",
        "view_marking_aggregation",
        "view_marking_shipping",
        "view_marking_tsd",
        "view_marking_labels",
        "view_reports",
    ],
    "brigadier": [
        "view_orders",
        "view_stocks",
        "view_chz_registry",
        "create_manual_chz_request",
        "delete_chz_request",
        "view_production",
        "create_production_order",
        "update_production_order",
        "delete_production_order",
        "request_production_supplies",
        "start_production",
        "complete_production",
        "transfer_production_to_stock",
        "request_production_chz",
        "view_production_order",
        "manage_production_labor",
        "view_employees",
        "manage_employee_shifts",
        "view_reports",
    ],
    "viewer": [],
}
